services:
  mysql:
    image: mysql:8.3
    env_file:
      - ./task-list-backend/.env
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3307:3306"
  task-list:
    build:
      dockerfile: Dockerfile
      context: ./task-list-backend
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./task-list-backend:/app
    command: ["sh", "-c", "pnpm run db:generate && pnpm run start:dev"]
  task-list-frontend:
    build:
      dockerfile: Dockerfile
      context: ./task-list-frontend
      target: development
    links:
      - task-list
    ports:
      - "3001:3001"
    volumes:
      - ./task-list-frontend:/app
      - /app/node_modules
    command: ["sh", "-c", "pnpm run dev"]
volumes:
  mysql:
