services:
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: task_list_root
      MYSQL_DATABASE: task_list
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3307:3306"

volumes:
  mysql:
